const ORDER_STATUS = { CANCELLED: 0, PENDING: 1, COMPLETED: 2 };
const TOUR_STATUS  = { HIDDEN: 0, ACTIVE: 1 };
const CATEGORY_STATUS = { HIDDEN: 0, ACTIVE: 1 };

module.exports = { ORDER_STATUS, TOUR_STATUS, CATEGORY_STATUS };
